// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { demos as dm0, frontmatter as fm0, toc as toc0, texts as txt0 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/.dumi/pages/index/components/demo2/node/outputNode.ts?type=meta';
import { demos as dm1, frontmatter as fm1, toc as toc1, texts as txt1 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/.dumi/pages/index/components/demo/node/circleNode.ts?type=meta';
import { demos as dm2, frontmatter as fm2, toc as toc2, texts as txt2 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/.dumi/pages/index/components/demo2/node/colorNode.ts?type=meta';
import { demos as dm3, frontmatter as fm3, toc as toc3, texts as txt3 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/.dumi/pages/index/components/demo2/node/levelNode.ts?type=meta';
import { demos as dm4, frontmatter as fm4, toc as toc4, texts as txt4 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/.dumi/pages/index/components/demo2/node/typeNode.ts?type=meta';
import { demos as dm5, frontmatter as fm5, toc as toc5, texts as txt5 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/.dumi/pages/index/components/Introduction/index.tsx?type=meta';
import { demos as dm6, frontmatter as fm6, toc as toc6, texts as txt6 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/.dumi/pages/index/components/demo/node/stepNode.ts?type=meta';
import { demos as dm7, frontmatter as fm7, toc as toc7, texts as txt7 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/.dumi/pages/enUS/components/Introduction/index.tsx?type=meta';
import { demos as dm8, frontmatter as fm8, toc as toc8, texts as txt8 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/.dumi/pages/index/components/animation/index.tsx?type=meta';
import { demos as dm9, frontmatter as fm9, toc as toc9, texts as txt9 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/.dumi/pages/index/components/demo2/index.tsx?type=meta';
import { demos as dm10, frontmatter as fm10, toc as toc10, texts as txt10 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/.dumi/pages/index/components/demo/index.tsx?type=meta';
import { demos as dm11, frontmatter as fm11, toc as toc11, texts as txt11 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/.dumi/pages/index/index.tsx?type=meta';
import { demos as dm12, frontmatter as fm12, toc as toc12, texts as txt12 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/.dumi/pages/index/inner.tsx?type=meta';
import { demos as dm13, frontmatter as fm13, toc as toc13, texts as txt13 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/.dumi/pages/enUS/index.tsx?type=meta';
import { demos as dm14, frontmatter as fm14, toc as toc14, texts as txt14 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/extension-insert-node-in-polyline.en-US.md?type=meta';
import { demos as dm15, frontmatter as fm15, toc as toc15, texts as txt15 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/extension-component-dnd-panel.en-US.md?type=meta';
import { demos as dm16, frontmatter as fm16, toc as toc16, texts as txt16 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/extension-component-selection.en-US.md?type=meta';
import { demos as dm17, frontmatter as fm17, toc as toc17, texts as txt17 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/extension-component-control.en-US.md?type=meta';
import { demos as dm18, frontmatter as fm18, toc as toc18, texts as txt18 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/extension-component-minimap.en-US.md?type=meta';
import { demos as dm19, frontmatter as fm19, toc as toc19, texts as txt19 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/extension-insert-node-in-polyline.md?type=meta';
import { demos as dm20, frontmatter as fm20, toc as toc20, texts as txt20 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/extension-component-custom.en-US.md?type=meta';
import { demos as dm21, frontmatter as fm21, toc as toc21, texts as txt21 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/extension-component-group.en-US.md?type=meta';
import { demos as dm22, frontmatter as fm22, toc as toc22, texts as txt22 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/extension-component-menu.en-US.md?type=meta';
import { demos as dm23, frontmatter as fm23, toc as toc23, texts as txt23 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/intermediate-silent-mode.en-US.md?type=meta';
import { demos as dm24, frontmatter as fm24, toc as toc24, texts as txt24 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/extension-component-dnd-panel.md?type=meta';
import { demos as dm25, frontmatter as fm25, toc as toc25, texts as txt25 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/extension-component-selection.md?type=meta';
import { demos as dm26, frontmatter as fm26, toc as toc26, texts as txt26 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/extension-bpmn-element.en-US.md?type=meta';
import { demos as dm27, frontmatter as fm27, toc as toc27, texts as txt27 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/extension-component-control.md?type=meta';
import { demos as dm28, frontmatter as fm28, toc as toc28, texts as txt28 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/extension-component-minimap.md?type=meta';
import { demos as dm29, frontmatter as fm29, toc as toc29, texts as txt29 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/extension-curved-edge.en-US.md?type=meta';
import { demos as dm30, frontmatter as fm30, toc as toc30, texts as txt30 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/extension-node-resize.en-US.md?type=meta';
import { demos as dm31, frontmatter as fm31, toc as toc31, texts as txt31 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/intermediate-keyboard.en-US.md?type=meta';
import { demos as dm32, frontmatter as fm32, toc as toc32, texts as txt32 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/intermediate-snapline.en-US.md?type=meta';
import { demos as dm33, frontmatter as fm33, toc as toc33, texts as txt33 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/extension-component-custom.md?type=meta';
import { demos as dm34, frontmatter as fm34, toc as toc34, texts as txt34 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/extension-component-group.md?type=meta';
import { demos as dm35, frontmatter as fm35, toc as toc35, texts as txt35 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/article/version-one-article.en-US.md?type=meta';
import { demos as dm36, frontmatter as fm36, toc as toc36, texts as txt36 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/extension-component-menu.md?type=meta';
import { demos as dm37, frontmatter as fm37, toc as toc37, texts as txt37 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/extension-snapshot.en-US.md?type=meta';
import { demos as dm38, frontmatter as fm38, toc as toc38, texts as txt38 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/intermediate-silent-mode.md?type=meta';
import { demos as dm39, frontmatter as fm39, toc as toc39, texts as txt39 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/extension-adapter.en-US.md?type=meta';
import { demos as dm40, frontmatter as fm40, toc as toc40, texts as txt40 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/intermediate-edge.en-US.md?type=meta';
import { demos as dm41, frontmatter as fm41, toc as toc41, texts as txt41 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/intermediate-node.en-US.md?type=meta';
import { demos as dm42, frontmatter as fm42, toc as toc42, texts as txt42 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/basic-background.en-US.md?type=meta';
import { demos as dm43, frontmatter as fm43, toc as toc43, texts as txt43 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/extension-bpmn-element.md?type=meta';
import { demos as dm44, frontmatter as fm44, toc as toc44, texts as txt44 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/intermediate-dnd.en-US.md?type=meta';
import { demos as dm45, frontmatter as fm45, toc as toc45, texts as txt45 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/extension-curved-edge.md?type=meta';
import { demos as dm46, frontmatter as fm46, toc as toc46, texts as txt46 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/extension-intro.en-US.md?type=meta';
import { demos as dm47, frontmatter as fm47, toc as toc47, texts as txt47 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/extension-node-resize.md?type=meta';
import { demos as dm48, frontmatter as fm48, toc as toc48, texts as txt48 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/getting-started.en-US.md?type=meta';
import { demos as dm49, frontmatter as fm49, toc as toc49, texts as txt49 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/intermediate-keyboard.md?type=meta';
import { demos as dm50, frontmatter as fm50, toc as toc50, texts as txt50 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/intermediate-snapline.md?type=meta';
import { demos as dm51, frontmatter as fm51, toc as toc51, texts as txt51 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/api/detail/constructor.en-US.md?type=meta';
import { demos as dm52, frontmatter as fm52, toc as toc52, texts as txt52 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/api/editConfigModelApi.en-US.md?type=meta';
import { demos as dm53, frontmatter as fm53, toc as toc53, texts as txt53 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/api/transformModelApi.en-US.md?type=meta';
import { demos as dm54, frontmatter as fm54, toc as toc54, texts as txt54 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/article/version-one-article.md?type=meta';
import { demos as dm55, frontmatter as fm55, toc as toc55, texts as txt55 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/release/one-point-one.en-US.md?type=meta';
import { demos as dm56, frontmatter as fm56, toc as toc56, texts as txt56 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/release/one-point-two.en-US.md?type=meta';
import { demos as dm57, frontmatter as fm57, toc as toc57, texts as txt57 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/extension-snapshot.md?type=meta';
import { demos as dm58, frontmatter as fm58, toc as toc58, texts as txt58 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/basic-class.en-US.md?type=meta';
import { demos as dm59, frontmatter as fm59, toc as toc59, texts as txt59 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/basic-event.en-US.md?type=meta';
import { demos as dm60, frontmatter as fm60, toc as toc60, texts as txt60 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/basic-theme.en-US.md?type=meta';
import { demos as dm61, frontmatter as fm61, toc as toc61, texts as txt61 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/extension-adapter.md?type=meta';
import { demos as dm62, frontmatter as fm62, toc as toc62, texts as txt62 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/intermediate-edge.md?type=meta';
import { demos as dm63, frontmatter as fm63, toc as toc63, texts as txt63 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/intermediate-node.md?type=meta';
import { demos as dm64, frontmatter as fm64, toc as toc64, texts as txt64 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/basic-background.md?type=meta';
import { demos as dm65, frontmatter as fm65, toc as toc65, texts as txt65 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/basic-edge.en-US.md?type=meta';
import { demos as dm66, frontmatter as fm66, toc as toc66, texts as txt66 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/basic-grid.en-US.md?type=meta';
import { demos as dm67, frontmatter as fm67, toc as toc67, texts as txt67 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/basic-node.en-US.md?type=meta';
import { demos as dm68, frontmatter as fm68, toc as toc68, texts as txt68 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/intermediate-dnd.md?type=meta';
import { demos as dm69, frontmatter as fm69, toc as toc69, texts as txt69 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/api/eventCenterApi.en-US.md?type=meta';
import { demos as dm70, frontmatter as fm70, toc as toc70, texts as txt70 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/article/NodeResize.en-US.md?type=meta';
import { demos as dm71, frontmatter as fm71, toc as toc71, texts as txt71 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/article/article-23.en-US.md?type=meta';
import { demos as dm72, frontmatter as fm72, toc as toc72, texts as txt72 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/extension-intro.md?type=meta';
import { demos as dm73, frontmatter as fm73, toc as toc73, texts as txt73 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/getting-started.md?type=meta';
import { demos as dm74, frontmatter as fm74, toc as toc74, texts as txt74 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/api/graphModelApi.en-US.md?type=meta';
import { demos as dm75, frontmatter as fm75, toc as toc75, texts as txt75 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/article/article01.en-US.md?type=meta';
import { demos as dm76, frontmatter as fm76, toc as toc76, texts as txt76 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/article/article02.en-US.md?type=meta';
import { demos as dm77, frontmatter as fm77, toc as toc77, texts as txt77 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/article/article03.en-US.md?type=meta';
import { demos as dm78, frontmatter as fm78, toc as toc78, texts as txt78 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/release/one-point.en-US.md?type=meta';
import { demos as dm79, frontmatter as fm79, toc as toc79, texts as txt79 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/api/detail/constructor.md?type=meta';
import { demos as dm80, frontmatter as fm80, toc as toc80, texts as txt80 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/api/detail/index.en-US.md?type=meta';
import { demos as dm81, frontmatter as fm81, toc as toc81, texts as txt81 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/api/edgeModelApi.en-US.md?type=meta';
import { demos as dm82, frontmatter as fm82, toc as toc82, texts as txt82 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/api/editConfigModelApi.md?type=meta';
import { demos as dm83, frontmatter as fm83, toc as toc83, texts as txt83 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/api/nodeModelApi.en-US.md?type=meta';
import { demos as dm84, frontmatter as fm84, toc as toc84, texts as txt84 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/api/transformModelApi.md?type=meta';
import { demos as dm85, frontmatter as fm85, toc as toc85, texts as txt85 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/release/one-point-one.md?type=meta';
import { demos as dm86, frontmatter as fm86, toc as toc86, texts as txt86 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/release/one-point-two.md?type=meta';
import { demos as dm87, frontmatter as fm87, toc as toc87, texts as txt87 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/examples/index.en-US.md?type=meta';
import { demos as dm88, frontmatter as fm88, toc as toc88, texts as txt88 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/basic-class.md?type=meta';
import { demos as dm89, frontmatter as fm89, toc as toc89, texts as txt89 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/basic-event.md?type=meta';
import { demos as dm90, frontmatter as fm90, toc as toc90, texts as txt90 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/basic-theme.md?type=meta';
import { demos as dm91, frontmatter as fm91, toc as toc91, texts as txt91 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/index.en-US.md?type=meta';
import { demos as dm92, frontmatter as fm92, toc as toc92, texts as txt92 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/basic-edge.md?type=meta';
import { demos as dm93, frontmatter as fm93, toc as toc93, texts as txt93 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/basic-grid.md?type=meta';
import { demos as dm94, frontmatter as fm94, toc as toc94, texts as txt94 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/basic-node.md?type=meta';
import { demos as dm95, frontmatter as fm95, toc as toc95, texts as txt95 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/api/eventCenterApi.md?type=meta';
import { demos as dm96, frontmatter as fm96, toc as toc96, texts as txt96 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/api/themeApi.en-US.md?type=meta';
import { demos as dm97, frontmatter as fm97, toc as toc97, texts as txt97 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/article/NodeResize.md?type=meta';
import { demos as dm98, frontmatter as fm98, toc as toc98, texts as txt98 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/article/article-23.md?type=meta';
import { demos as dm99, frontmatter as fm99, toc as toc99, texts as txt99 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/api/graphModelApi.md?type=meta';
import { demos as dm100, frontmatter as fm100, toc as toc100, texts as txt100 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/article/article01.md?type=meta';
import { demos as dm101, frontmatter as fm101, toc as toc101, texts as txt101 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/article/article02.md?type=meta';
import { demos as dm102, frontmatter as fm102, toc as toc102, texts as txt102 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/article/article03.md?type=meta';
import { demos as dm103, frontmatter as fm103, toc as toc103, texts as txt103 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/release/one-point.md?type=meta';
import { demos as dm104, frontmatter as fm104, toc as toc104, texts as txt104 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/api/detail/index.md?type=meta';
import { demos as dm105, frontmatter as fm105, toc as toc105, texts as txt105 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/api/edgeModelApi.md?type=meta';
import { demos as dm106, frontmatter as fm106, toc as toc106, texts as txt106 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/api/nodeModelApi.md?type=meta';
import { demos as dm107, frontmatter as fm107, toc as toc107, texts as txt107 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/api/index.en-US.md?type=meta';
import { demos as dm108, frontmatter as fm108, toc as toc108, texts as txt108 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/examples/index.md?type=meta';
import { demos as dm109, frontmatter as fm109, toc as toc109, texts as txt109 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/tutorial/index.md?type=meta';
import { demos as dm110, frontmatter as fm110, toc as toc110, texts as txt110 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/api/themeApi.md?type=meta';
import { demos as dm111, frontmatter as fm111, toc as toc111, texts as txt111 } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/sites/logicflow-docs/docs/api/index.md?type=meta';

export { components } from './atoms';
export { tabs } from './tabs';

export const filesMeta = {
  'index/components/demo2/node/outputNode': {
    frontmatter: fm0,
    toc: toc0,
    texts: txt0,
    demos: dm0,
  },
  'index/components/demo/node/circleNode': {
    frontmatter: fm1,
    toc: toc1,
    texts: txt1,
    demos: dm1,
  },
  'index/components/demo2/node/colorNode': {
    frontmatter: fm2,
    toc: toc2,
    texts: txt2,
    demos: dm2,
  },
  'index/components/demo2/node/levelNode': {
    frontmatter: fm3,
    toc: toc3,
    texts: txt3,
    demos: dm3,
  },
  'index/components/demo2/node/typeNode': {
    frontmatter: fm4,
    toc: toc4,
    texts: txt4,
    demos: dm4,
  },
  'index/components/Introduction/index': {
    frontmatter: fm5,
    toc: toc5,
    texts: txt5,
    demos: dm5,
  },
  'index/components/demo/node/stepNode': {
    frontmatter: fm6,
    toc: toc6,
    texts: txt6,
    demos: dm6,
  },
  'enUS/components/Introduction/index': {
    frontmatter: fm7,
    toc: toc7,
    texts: txt7,
    demos: dm7,
  },
  'index/components/animation/index': {
    frontmatter: fm8,
    toc: toc8,
    texts: txt8,
    demos: dm8,
  },
  'index/components/demo2/index': {
    frontmatter: fm9,
    toc: toc9,
    texts: txt9,
    demos: dm9,
  },
  'index/components/demo/index': {
    frontmatter: fm10,
    toc: toc10,
    texts: txt10,
    demos: dm10,
  },
  'index/index': {
    frontmatter: fm11,
    toc: toc11,
    texts: txt11,
    demos: dm11,
  },
  'index/inner': {
    frontmatter: fm12,
    toc: toc12,
    texts: txt12,
    demos: dm12,
  },
  'enUS/index': {
    frontmatter: fm13,
    toc: toc13,
    texts: txt13,
    demos: dm13,
  },
  'docs/tutorial/extension-insert-node-in-polyline.en-US': {
    frontmatter: fm14,
    toc: toc14,
    texts: txt14,
    demos: dm14,
  },
  'docs/tutorial/extension-component-dnd-panel.en-US': {
    frontmatter: fm15,
    toc: toc15,
    texts: txt15,
    demos: dm15,
  },
  'docs/tutorial/extension-component-selection.en-US': {
    frontmatter: fm16,
    toc: toc16,
    texts: txt16,
    demos: dm16,
  },
  'docs/tutorial/extension-component-control.en-US': {
    frontmatter: fm17,
    toc: toc17,
    texts: txt17,
    demos: dm17,
  },
  'docs/tutorial/extension-component-minimap.en-US': {
    frontmatter: fm18,
    toc: toc18,
    texts: txt18,
    demos: dm18,
  },
  'docs/tutorial/extension-insert-node-in-polyline': {
    frontmatter: fm19,
    toc: toc19,
    texts: txt19,
    demos: dm19,
  },
  'docs/tutorial/extension-component-custom.en-US': {
    frontmatter: fm20,
    toc: toc20,
    texts: txt20,
    demos: dm20,
  },
  'docs/tutorial/extension-component-group.en-US': {
    frontmatter: fm21,
    toc: toc21,
    texts: txt21,
    demos: dm21,
  },
  'docs/tutorial/extension-component-menu.en-US': {
    frontmatter: fm22,
    toc: toc22,
    texts: txt22,
    demos: dm22,
  },
  'docs/tutorial/intermediate-silent-mode.en-US': {
    frontmatter: fm23,
    toc: toc23,
    texts: txt23,
    demos: dm23,
  },
  'docs/tutorial/extension-component-dnd-panel': {
    frontmatter: fm24,
    toc: toc24,
    texts: txt24,
    demos: dm24,
  },
  'docs/tutorial/extension-component-selection': {
    frontmatter: fm25,
    toc: toc25,
    texts: txt25,
    demos: dm25,
  },
  'docs/tutorial/extension-bpmn-element.en-US': {
    frontmatter: fm26,
    toc: toc26,
    texts: txt26,
    demos: dm26,
  },
  'docs/tutorial/extension-component-control': {
    frontmatter: fm27,
    toc: toc27,
    texts: txt27,
    demos: dm27,
  },
  'docs/tutorial/extension-component-minimap': {
    frontmatter: fm28,
    toc: toc28,
    texts: txt28,
    demos: dm28,
  },
  'docs/tutorial/extension-curved-edge.en-US': {
    frontmatter: fm29,
    toc: toc29,
    texts: txt29,
    demos: dm29,
  },
  'docs/tutorial/extension-node-resize.en-US': {
    frontmatter: fm30,
    toc: toc30,
    texts: txt30,
    demos: dm30,
  },
  'docs/tutorial/intermediate-keyboard.en-US': {
    frontmatter: fm31,
    toc: toc31,
    texts: txt31,
    demos: dm31,
  },
  'docs/tutorial/intermediate-snapline.en-US': {
    frontmatter: fm32,
    toc: toc32,
    texts: txt32,
    demos: dm32,
  },
  'docs/tutorial/extension-component-custom': {
    frontmatter: fm33,
    toc: toc33,
    texts: txt33,
    demos: dm33,
  },
  'docs/tutorial/extension-component-group': {
    frontmatter: fm34,
    toc: toc34,
    texts: txt34,
    demos: dm34,
  },
  'docs/article/version-one-article.en-US': {
    frontmatter: fm35,
    toc: toc35,
    texts: txt35,
    demos: dm35,
  },
  'docs/tutorial/extension-component-menu': {
    frontmatter: fm36,
    toc: toc36,
    texts: txt36,
    demos: dm36,
  },
  'docs/tutorial/extension-snapshot.en-US': {
    frontmatter: fm37,
    toc: toc37,
    texts: txt37,
    demos: dm37,
  },
  'docs/tutorial/intermediate-silent-mode': {
    frontmatter: fm38,
    toc: toc38,
    texts: txt38,
    demos: dm38,
  },
  'docs/tutorial/extension-adapter.en-US': {
    frontmatter: fm39,
    toc: toc39,
    texts: txt39,
    demos: dm39,
  },
  'docs/tutorial/intermediate-edge.en-US': {
    frontmatter: fm40,
    toc: toc40,
    texts: txt40,
    demos: dm40,
  },
  'docs/tutorial/intermediate-node.en-US': {
    frontmatter: fm41,
    toc: toc41,
    texts: txt41,
    demos: dm41,
  },
  'docs/tutorial/basic-background.en-US': {
    frontmatter: fm42,
    toc: toc42,
    texts: txt42,
    demos: dm42,
  },
  'docs/tutorial/extension-bpmn-element': {
    frontmatter: fm43,
    toc: toc43,
    texts: txt43,
    demos: dm43,
  },
  'docs/tutorial/intermediate-dnd.en-US': {
    frontmatter: fm44,
    toc: toc44,
    texts: txt44,
    demos: dm44,
  },
  'docs/tutorial/extension-curved-edge': {
    frontmatter: fm45,
    toc: toc45,
    texts: txt45,
    demos: dm45,
  },
  'docs/tutorial/extension-intro.en-US': {
    frontmatter: fm46,
    toc: toc46,
    texts: txt46,
    demos: dm46,
  },
  'docs/tutorial/extension-node-resize': {
    frontmatter: fm47,
    toc: toc47,
    texts: txt47,
    demos: dm47,
  },
  'docs/tutorial/getting-started.en-US': {
    frontmatter: fm48,
    toc: toc48,
    texts: txt48,
    demos: dm48,
  },
  'docs/tutorial/intermediate-keyboard': {
    frontmatter: fm49,
    toc: toc49,
    texts: txt49,
    demos: dm49,
  },
  'docs/tutorial/intermediate-snapline': {
    frontmatter: fm50,
    toc: toc50,
    texts: txt50,
    demos: dm50,
  },
  'docs/api/detail/constructor.en-US': {
    frontmatter: fm51,
    toc: toc51,
    texts: txt51,
    demos: dm51,
  },
  'docs/api/editConfigModelApi.en-US': {
    frontmatter: fm52,
    toc: toc52,
    texts: txt52,
    demos: dm52,
  },
  'docs/api/transformModelApi.en-US': {
    frontmatter: fm53,
    toc: toc53,
    texts: txt53,
    demos: dm53,
  },
  'docs/article/version-one-article': {
    frontmatter: fm54,
    toc: toc54,
    texts: txt54,
    demos: dm54,
  },
  'docs/release/one-point-one.en-US': {
    frontmatter: fm55,
    toc: toc55,
    texts: txt55,
    demos: dm55,
  },
  'docs/release/one-point-two.en-US': {
    frontmatter: fm56,
    toc: toc56,
    texts: txt56,
    demos: dm56,
  },
  'docs/tutorial/extension-snapshot': {
    frontmatter: fm57,
    toc: toc57,
    texts: txt57,
    demos: dm57,
  },
  'docs/tutorial/basic-class.en-US': {
    frontmatter: fm58,
    toc: toc58,
    texts: txt58,
    demos: dm58,
  },
  'docs/tutorial/basic-event.en-US': {
    frontmatter: fm59,
    toc: toc59,
    texts: txt59,
    demos: dm59,
  },
  'docs/tutorial/basic-theme.en-US': {
    frontmatter: fm60,
    toc: toc60,
    texts: txt60,
    demos: dm60,
  },
  'docs/tutorial/extension-adapter': {
    frontmatter: fm61,
    toc: toc61,
    texts: txt61,
    demos: dm61,
  },
  'docs/tutorial/intermediate-edge': {
    frontmatter: fm62,
    toc: toc62,
    texts: txt62,
    demos: dm62,
  },
  'docs/tutorial/intermediate-node': {
    frontmatter: fm63,
    toc: toc63,
    texts: txt63,
    demos: dm63,
  },
  'docs/tutorial/basic-background': {
    frontmatter: fm64,
    toc: toc64,
    texts: txt64,
    demos: dm64,
  },
  'docs/tutorial/basic-edge.en-US': {
    frontmatter: fm65,
    toc: toc65,
    texts: txt65,
    demos: dm65,
  },
  'docs/tutorial/basic-grid.en-US': {
    frontmatter: fm66,
    toc: toc66,
    texts: txt66,
    demos: dm66,
  },
  'docs/tutorial/basic-node.en-US': {
    frontmatter: fm67,
    toc: toc67,
    texts: txt67,
    demos: dm67,
  },
  'docs/tutorial/intermediate-dnd': {
    frontmatter: fm68,
    toc: toc68,
    texts: txt68,
    demos: dm68,
  },
  'docs/api/eventCenterApi.en-US': {
    frontmatter: fm69,
    toc: toc69,
    texts: txt69,
    demos: dm69,
  },
  'docs/article/NodeResize.en-US': {
    frontmatter: fm70,
    toc: toc70,
    texts: txt70,
    demos: dm70,
  },
  'docs/article/article-23.en-US': {
    frontmatter: fm71,
    toc: toc71,
    texts: txt71,
    demos: dm71,
  },
  'docs/tutorial/extension-intro': {
    frontmatter: fm72,
    toc: toc72,
    texts: txt72,
    demos: dm72,
  },
  'docs/tutorial/getting-started': {
    frontmatter: fm73,
    toc: toc73,
    texts: txt73,
    demos: dm73,
  },
  'docs/api/graphModelApi.en-US': {
    frontmatter: fm74,
    toc: toc74,
    texts: txt74,
    demos: dm74,
  },
  'docs/article/article01.en-US': {
    frontmatter: fm75,
    toc: toc75,
    texts: txt75,
    demos: dm75,
  },
  'docs/article/article02.en-US': {
    frontmatter: fm76,
    toc: toc76,
    texts: txt76,
    demos: dm76,
  },
  'docs/article/article03.en-US': {
    frontmatter: fm77,
    toc: toc77,
    texts: txt77,
    demos: dm77,
  },
  'docs/release/one-point.en-US': {
    frontmatter: fm78,
    toc: toc78,
    texts: txt78,
    demos: dm78,
  },
  'docs/api/detail/constructor': {
    frontmatter: fm79,
    toc: toc79,
    texts: txt79,
    demos: dm79,
  },
  'docs/api/detail/index.en-US': {
    frontmatter: fm80,
    toc: toc80,
    texts: txt80,
    demos: dm80,
  },
  'docs/api/edgeModelApi.en-US': {
    frontmatter: fm81,
    toc: toc81,
    texts: txt81,
    demos: dm81,
  },
  'docs/api/editConfigModelApi': {
    frontmatter: fm82,
    toc: toc82,
    texts: txt82,
    demos: dm82,
  },
  'docs/api/nodeModelApi.en-US': {
    frontmatter: fm83,
    toc: toc83,
    texts: txt83,
    demos: dm83,
  },
  'docs/api/transformModelApi': {
    frontmatter: fm84,
    toc: toc84,
    texts: txt84,
    demos: dm84,
  },
  'docs/release/one-point-one': {
    frontmatter: fm85,
    toc: toc85,
    texts: txt85,
    demos: dm85,
  },
  'docs/release/one-point-two': {
    frontmatter: fm86,
    toc: toc86,
    texts: txt86,
    demos: dm86,
  },
  'docs/examples/index.en-US': {
    frontmatter: fm87,
    toc: toc87,
    texts: txt87,
    demos: dm87,
  },
  'docs/tutorial/basic-class': {
    frontmatter: fm88,
    toc: toc88,
    texts: txt88,
    demos: dm88,
  },
  'docs/tutorial/basic-event': {
    frontmatter: fm89,
    toc: toc89,
    texts: txt89,
    demos: dm89,
  },
  'docs/tutorial/basic-theme': {
    frontmatter: fm90,
    toc: toc90,
    texts: txt90,
    demos: dm90,
  },
  'docs/tutorial/index.en-US': {
    frontmatter: fm91,
    toc: toc91,
    texts: txt91,
    demos: dm91,
  },
  'docs/tutorial/basic-edge': {
    frontmatter: fm92,
    toc: toc92,
    texts: txt92,
    demos: dm92,
  },
  'docs/tutorial/basic-grid': {
    frontmatter: fm93,
    toc: toc93,
    texts: txt93,
    demos: dm93,
  },
  'docs/tutorial/basic-node': {
    frontmatter: fm94,
    toc: toc94,
    texts: txt94,
    demos: dm94,
  },
  'docs/api/eventCenterApi': {
    frontmatter: fm95,
    toc: toc95,
    texts: txt95,
    demos: dm95,
  },
  'docs/api/themeApi.en-US': {
    frontmatter: fm96,
    toc: toc96,
    texts: txt96,
    demos: dm96,
  },
  'docs/article/NodeResize': {
    frontmatter: fm97,
    toc: toc97,
    texts: txt97,
    demos: dm97,
  },
  'docs/article/article-23': {
    frontmatter: fm98,
    toc: toc98,
    texts: txt98,
    demos: dm98,
  },
  'docs/api/graphModelApi': {
    frontmatter: fm99,
    toc: toc99,
    texts: txt99,
    demos: dm99,
  },
  'docs/article/article01': {
    frontmatter: fm100,
    toc: toc100,
    texts: txt100,
    demos: dm100,
  },
  'docs/article/article02': {
    frontmatter: fm101,
    toc: toc101,
    texts: txt101,
    demos: dm101,
  },
  'docs/article/article03': {
    frontmatter: fm102,
    toc: toc102,
    texts: txt102,
    demos: dm102,
  },
  'docs/release/one-point': {
    frontmatter: fm103,
    toc: toc103,
    texts: txt103,
    demos: dm103,
  },
  'docs/api/detail/index': {
    frontmatter: fm104,
    toc: toc104,
    texts: txt104,
    demos: dm104,
  },
  'docs/api/edgeModelApi': {
    frontmatter: fm105,
    toc: toc105,
    texts: txt105,
    demos: dm105,
  },
  'docs/api/nodeModelApi': {
    frontmatter: fm106,
    toc: toc106,
    texts: txt106,
    demos: dm106,
  },
  'docs/api/index.en-US': {
    frontmatter: fm107,
    toc: toc107,
    texts: txt107,
    demos: dm107,
  },
  'docs/examples/index': {
    frontmatter: fm108,
    toc: toc108,
    texts: txt108,
    demos: dm108,
  },
  'docs/tutorial/index': {
    frontmatter: fm109,
    toc: toc109,
    texts: txt109,
    demos: dm109,
  },
  'docs/api/themeApi': {
    frontmatter: fm110,
    toc: toc110,
    texts: txt110,
    demos: dm110,
  },
  'docs/api/index': {
    frontmatter: fm111,
    toc: toc111,
    texts: txt111,
    demos: dm111,
  },
}

// generate demos data in runtime, for reuse route.id to reduce bundle size
export const demos = Object.entries(filesMeta).reduce((acc, [id, meta]) => {
  // append route id to demo
  Object.values(meta.demos).forEach((demo) => {
    demo.routeId = id;
  });
  // merge demos
  Object.assign(acc, meta.demos);

  // remove demos from meta, to avoid deep clone demos in umi routes/children compatible logic
  delete meta.demos;

  return acc;
}, {});
