// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/home","parentId":"ant-design-pro-layout","id":"1"},"2":{"name":"首页","path":"/home","parentId":"ant-design-pro-layout","id":"2"},"3":{"name":"节点","path":"/node","parentId":"ant-design-pro-layout","id":"3"},"4":{"path":"node","redirect":"node/native","parentId":"3","id":"4"},"5":{"path":"/node/native","name":"内置节点","parentId":"3","id":"5"},"6":{"path":"/node/custom","name":"自定义节点","parentId":"3","id":"6"},"7":{"path":"node/custom","redirect":"node/custom/rect","parentId":"6","id":"7"},"8":{"path":"/node/custom/rect","name":"矩形节点","parentId":"6","id":"8"},"9":{"path":"/node/custom/ellipse","name":"椭圆节点","parentId":"6","id":"9"},"10":{"path":"/node/custom/icon","name":"图标节点","parentId":"6","id":"10"},"11":{"path":"/node/custom/image","name":"图像节点","parentId":"6","id":"11"},"12":{"path":"/node/custom/html","name":"HTML节点","parentId":"6","id":"12"},"13":{"path":"/node/custom/theme","name":"自定义主题","parentId":"6","id":"13"},"14":{"name":"插件系统","path":"/extension","parentId":"ant-design-pro-layout","id":"14"},"15":{"path":"extension","redirect":"extension/control","parentId":"14","id":"15"},"16":{"path":"/extension/control","name":"Control 插件","parentId":"14","id":"16"},"17":{"path":"/extension/menu","name":"Menu 插件","parentId":"14","id":"17"},"18":{"path":"/extension/dnd-panel","name":"DndPanel 插件","parentId":"14","id":"18"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Home__index" */'@/pages/Home/index.tsx')),
'3': React.lazy(() => import( './EmptyRoute')),
'4': React.lazy(() => import( './EmptyRoute')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Node__Native__index" */'@/pages/Node/Native/index.tsx')),
'6': React.lazy(() => import( './EmptyRoute')),
'7': React.lazy(() => import( './EmptyRoute')),
'8': React.lazy(() => import(/* webpackChunkName: "p__Node__Custom__Rect__index" */'@/pages/Node/Custom/Rect/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__Node__Custom__Ellipse__index" */'@/pages/Node/Custom/Ellipse/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__Node__Custom__Icon__index" */'@/pages/Node/Custom/Icon/index.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__Node__Custom__Image__index" */'@/pages/Node/Custom/Image/index.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__Node__Custom__Html__index" */'@/pages/Node/Custom/Html/index.tsx')),
'13': React.lazy(() => import(/* webpackChunkName: "p__Node__Custom__Theme__index" */'@/pages/Node/Custom/Theme/index.tsx')),
'14': React.lazy(() => import( './EmptyRoute')),
'15': React.lazy(() => import( './EmptyRoute')),
'16': React.lazy(() => import(/* webpackChunkName: "p__Extension__Control__index" */'@/pages/Extension/Control/index.tsx')),
'17': React.lazy(() => import(/* webpackChunkName: "p__Extension__Menu__index" */'@/pages/Extension/Menu/index.tsx')),
'18': React.lazy(() => import(/* webpackChunkName: "p__Extension__DndPanel__index" */'@/pages/Extension/DndPanel/index.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow/examples/react-umi-app/src/.umi/plugin-layout/Layout.tsx')),
},
  };
}
