// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: (typeof import('element-plus/es'))['ElButton']
    ElCollapse: (typeof import('element-plus/es'))['ElCollapse']
    ElCollapseItem: (typeof import('element-plus/es'))['ElCollapseItem']
    ElInput: (typeof import('element-plus/es'))['ElInput']
    FlowChart: (typeof import('./src/components/FlowChart.vue'))['default']
    Palette: (typeof import('./src/components/node-red/tools/Palette.vue'))['default']
    Setting: (typeof import('./src/components/node-red/tools/Setting.vue'))['default']
    Undefined: (typeof import('./src/components/index.vue'))['default']
    VueNode: (typeof import('./src/components/node-red/nodes/VueNode.vue'))['default']
  }
}

export {}
