// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React, { useState, useEffect, useRef } from 'react';
import { useOutlet, history } from 'dumi';
import { SiteContext } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/node_modules/.pnpm/dumi@2.2.13_@babel+core@7.23.2_@types+node@20.4.4_@types+react@18.2.17_eslint@8.48.0_jest@29._62mlhybvk6k52sxatmqmsmqghi/node_modules/dumi/dist/client/theme-api/context.js';
import { demos, components } from '../meta';
import { locales } from '../locales/config';

const entryExports = {
  
  
};

export default function DumiContextWrapper() {
  const outlet = useOutlet();
  const [loading, setLoading] = useState(false);
  const prev = useRef(history.location.pathname);

  useEffect(() => {
    return history.listen((next) => {
      if (next.location.pathname !== prev.current) {
        prev.current = next.location.pathname;

        // scroll to top when route changed
        document.documentElement.scrollTo(0, 0);
      }
    });
  }, []);

  return (
    <SiteContext.Provider value={{
      pkg: {"name":"logicflow-sites","description":"LogicFlow sites deployed on gh-pages","version":"1.2.x","license":"MIT","repository":"https://github.com/didi/LogicFlow","authors":["boyongjiong@gmail.com"]},
      historyType: "browser",
      entryExports,
      demos,
      components,
      locales,
      loading,
      setLoading,
      hostname: undefined,
      themeConfig: {"footer":"Copyright © 2024 | Powered by LogicFlow Team","prefersColor":{"default":"light","switch":true},"nprogress":true,"lastUpdated":true,"name":"LogicFlow","logo":"/logo.png","rtl":true,"nav":{"zh-CN":[{"title":"文档","link":"/tutorial"},{"title":"API","link":"/api"},{"title":"示例","link":"/examples"},{"title":"文章","link":"/article/article01"}],"en-US":[{"title":"Tutorial","link":"/en-US/tutorial"},{"title":"API","link":"/en-US/api"},{"title":"Examples","link":"/en-US/examples"},{"title":"Article","link":"/en-US/article/article01"}]},"socialLinks":{"github":"https://github.com/didi/LogicFlow"},"editLink":"https://github.com/didi/LogicFlow/edit/main/{filename}"},
      _2_level_nav_available: true,
    }}>
      {outlet}
    </SiteContext.Provider>
  );
}
