// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/r0ger1tlearn/WorkSpace/Github/DiDi/logicflow-next/node_modules/.pnpm/dumi@2.2.13_@babel+core@7.23.2_@types+node@20.4.4_@types+react@18.2.17_eslint@8.48.0_jest@29._62mlhybvk6k52sxatmqmsmqghi/node_modules/dumi/theme-default/slots/RtlSwitch/index.js';
